# Generated by Django 3.0.6 on 2020-05-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_author', models.CharField(max_length=30)),
                ('post_title', models.CharField(max_length=30)),
                ('post_text', models.CharField(max_length=200)),
                ('post_id', models.IntegerField()),
            ],
        ),
    ]
